### ISSUE TITLE
Feature install environment bases

### ISSUE THREAD

**Issue by felipe-passada** [felipe-passada/env_conf#1]
# Todo

## Tools
- [ ] Install tools based on a list "To be installed"
  zsh
  osmyzsh
  fuzzy finder and regrep
  fira code for vscode
  hacker nerd font for terminal

- [ ] Install NVM and Java/Kotlin SDK
## Gnome

- [ ] Set the dark theme
- [ ] install some extensions
